student_classes = {
    "primary 1": {
        "total attendance": 4,
        "total projects": 5,
        "teacher": "",
        "teacher_id": "",
        "class subjects": [
            "English studies",
            "Mathematics",
            "Basic Science",
            "Health Education",
            "CRS",
            "Social Studies",
            "Yoruba",
            "Cultural and Creative Arts",
            "Nigerian History",
        ],
        "students": [],
    },
    "primary 2": {
        "total attendance": 5,
        "total projects": 2,
        "teacher": "",
        "teacher_id": "",
        "class subjects": [
            "English studies",
            "Mathematics",
            "Basic Science",
            "Health Education",
            "CRS",
            "Social Studies",
            "Yoruba",
            "Cultural and Creative Arts",
            "Nigerian History",
        ],
        "students": [],
    },
    "primary 3": {
        "total attendance": 9,
        "total projects": 4,
        "teacher": "",
        "teacher_id": "",
        "class subjects": [
            "English studies",
            "Mathematics",
            "Basic Science",
            "Health Education",
            "CRS",
            "Social Studies",
            "Yoruba",
            "Cultural and Creative Arts",
            "Nigerian History",
        ],
        "students": [],
    },
    "primary 4": {
        "total attendance": 20,
        "total projects": 5,
        "teacher": "",
        "teacher_id": "",
        "class subjects": [
            "English studies",
            "Mathematics",
            "Basic Science",
            "Health Education",
            "CRS",
            "Social Studies",
            "Yoruba",
            "Cultural and Creative Arts",
            "Nigerian History",
            "Basic Digital Literacy",
            "Provocational studies",
        ],
        "students": [],
    },
    "primary 5": {
        "total attendance": 30,
        "total projects": 4,
        "teacher": "",
        "teacher_id": "",
        "class subjects": [
            "English studies",
            "Mathematics",
            "Basic Science",
            "Health Education",
            "CRS",
            "Social Studies",
            "Yoruba",
            "Cultural and Creative Arts",
            "Nigerian History",
            "Basic Digital Literacy",
            "Provocational studies",
        ],
        "students": [],
    },
    "primary 6": {
        "total attendance": 60,
        "total projects": 3,
        "teacher": "",
        "teacher_id": "",
        "class subjects": [
            "English studies",
            "Mathematics",
            "Basic Science",
            "Health Education",
            "CRS",
            "Social Studies",
            "Yoruba",
            "Cultural and Creative Arts",
            "Nigerian History",
            "Basic Digital Literacy",
            "Provocational studies",
        ],
        "students": [],
    },
}